# This module defines the TTSService class, which provides functionality for generating text-to-speech audio files using the OpenAI API. The service generates audio files based on input text and caches them locally to avoid redundant generation. It includes methods for hashing input text to create unique filenames, checking if audio files are ready, and generating audio content asynchronously. The generated audio files are stored in a specified directory and can be accessed via URLs.
# Import necessary libraries and modules, including os for file handling, hashlib for hashing text, AsyncOpenAI for interacting with the OpenAI API, and dotenv for loading environment variables.
import os
import hashlib
from openai import AsyncOpenAI
from dotenv import load_dotenv

# Load environment variables from a .env file to access the OpenAI API key and other configurations.
load_dotenv()

client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# Define constants for the audio directory and the default voice to be used for text-to-speech generation. The audio directory is where the generated audio files will be stored, and the default voice can be configured via an environment variable.
AUDIO_DIR = "media/audio"
DEFAULT_VOICE = os.getenv("OPENAI_TTS_VOICE", "marin").strip().lower()

# Define the TTSService class that provides methods for generating text-to-speech audio files. The class includes methods for hashing input text to create unique filenames, checking if audio files are ready, and generating audio content asynchronously using the OpenAI API. The generated audio files are stored in a specified directory and can be accessed via URLs.
class TTSService:
    
    # Initialize the TTSService by creating the audio directory if it does not already exist. This ensures that there is a designated location for storing the generated audio files.
    def __init__(self):
        os.makedirs(AUDIO_DIR, exist_ok=True)

    # This private method takes a string of text as input and returns a unique hash of that text using the MD5 hashing algorithm. The hash is generated by stripping any leading or trailing whitespace from the input text, encoding it in UTF-8 format, and then applying the MD5 hash function. The resulting hash is used to create unique filenames for the generated audio files, ensuring that the same input text will always produce the same filename.
    def _hash(self, text: str) -> str:
        return hashlib.md5(text.strip().encode("utf-8")).hexdigest()

    # This private method checks if an audio file at the specified path is ready for use. It does this by verifying that the file exists and that its size is greater than 5000 bytes, which is a heuristic to ensure that the file is not empty or corrupted. If the file does not exist or is too small, it returns False, indicating that the audio file is not ready; otherwise, it returns True.
    def _audio_file_ready(self, path: str) -> bool:
        try:
            return os.path.exists(path) and os.path.getsize(path) > 5000
        except Exception:
            return False

    # This asynchronous method generates a text-to-speech audio file based on the input text. It first checks if the input text is empty and returns an empty string if it is. Then, it generates a unique filename for the audio file using the _hash method and constructs the file path and URL for accessing the audio. If the audio file already exists and is ready, it returns the URL. Otherwise, it sends a request to the OpenAI API to create the speech audio using the specified model and voice. The generated audio content is saved to a temporary file, which is then checked for readiness before being renamed to the final path. If any step fails, it returns an empty string.
    async def gen(self, text: str) -> str:
        text = (text or "").strip()

        if not text:
            return ""

        filename = self._hash(text) + ".mp3"
        path = os.path.join(AUDIO_DIR, filename)
        url = "/media/audio/" + filename

        if self._audio_file_ready(path):
            return url

        response = await client.audio.speech.create(
            model="gpt-4o-mini-tts",
            voice=DEFAULT_VOICE,
            input=text,
        )

        audio_content = getattr(response, "content", None)

        if not audio_content:
            return ""

        temp_path = path + ".tmp"

       # Save the generated audio content to a temporary file and check if it is ready before renaming it to the final path. This ensures that only fully generated and valid audio files are stored in the designated directory. If the temporary file is not ready, it is removed, and an empty string is returned.
        with open(temp_path, "wb") as f:
            f.write(audio_content)

        if not self._audio_file_ready(temp_path):
            try:
                os.remove(temp_path)
            except Exception:
                pass

            return ""

        os.replace(temp_path, path)

        if not self._audio_file_ready(path):
            return ""

        return url