# Generated by Django 5.1 on 2026-04-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reading_logs_and_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypage',
            old_name='text',
            new_name='narration_text',
        ),
        migrations.RemoveField(
            model_name='child',
            name='age',
        ),
        migrations.AddField(
            model_name='child',
            name='age_group',
            field=models.CharField(choices=[('4-5', '4-5'), ('6-7', '6-7'), ('8-9', '8-9')], default='6-7', max_length=3),
        ),
        migrations.AddField(
            model_name='story',
            name='custom_behavior',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='story',
            name='raw_story_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storypage',
            name='audio_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('generating_story', 'Generating Story'), ('generating_images', 'Generating Images'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='storypage',
            name='illustration_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
