# Generated by Django 6.0.4 on 2026-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_story_pdf_file_story_pdf_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pdf_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='pdf_progress',
            field=models.IntegerField(default=0),
        ),
    ]
