# Generated by Django 6.0.4 on 2026-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_story_pdf_error_story_pdf_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypage',
            name='audio_text_hash',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
